#version: '3'
#services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#      - "9300:9300"