# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build and Deploy docker container to oracle cloud ubuntu server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Gradle
        run: |
          ./gradlew build
        working-directory: ./

  login-docker-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-docker-image:
    needs: login-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: build docker image
        run: |
          docker build --file /app/Dockerfile -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}} .

  push-docker-image:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}} .

  deploy-server:
    needs: push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Oracle Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /app/freight/
            docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}}
            docker run -d --name freight-for-centos8 -p 3000:3000 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}} 

